package rars.events

import rars.events.EventReason.*

/**
 * Represents a memory error. This is generated by the simulator when the
 * source code references a memory address not valid for the context.
 */
data class MemoryError(
    val message: String,
    val reason: EventReason,
    val address: Int
) {
    init {
        when (reason) {
            INSTRUCTION_ACCESS_FAULT,
            INSTRUCTION_ADDR_MISALIGNED,
            LOAD_ACCESS_FAULT,
            LOAD_ADDRESS_MISALIGNED,
            STORE_ACCESS_FAULT,
            STORE_ADDRESS_MISALIGNED -> Unit
            else -> error("This exception reason is not allowed")
        }
    }
}
